name: Publish

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Publish
    strategy:
      matrix:
        os: [ubuntu-latest]
        scala: [2.12.15]
        java: [zulu@1.17]
    runs-on: harana-dev-linux
    steps:

      - name: Cleanup Ref
        id: ref
        uses: frabert/replace-string-action@v1.2
        with:
          pattern: 'refs\/\w+\/(.*)'
          string: ${{ github.ref }}
          replace-with: '$1'

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Cache
        run: |
          mkdir ~/.cache
          mkdir ~/.ivy2
          ln -s /opt/cache/coursier_cache ~/.cache/coursier
          ln -s /opt/cache/ivy2_cache ~/.ivy2/cache

      - name: Publish Packages
        env:
          GITHUB_TOKEN: ${{ secrets.WRITE_PACKAGES_TOKEN }}
        run: sbt ++${{ matrix.scala }} publish

      - name: Get Scala Major Version
        id: scala
        uses: actions-ecosystem/action-regex-match@v2
        with:
          regex: '([0-9]+\.[0-9]+)\.[0-9]+'
          text: ${{ matrix.scala }}

      - name: Remove Older Snapshots
        uses: smartsquaregmbh/delete-old-packages@v0.2.0
        with:
          keep: 2
          version-pattern: ".+?SNAPSHOT"
          names: |
            com.harana.sbt.common_${{ steps.scala.outputs.group1 }}_1.0
            com.harana.sbt.js_${{ steps.scala.outputs.group1 }}_1.0
            com.harana.sbt.jvm_${{ steps.scala.outputs.group1 }}_1.0
            com.harana.sbt.js_jvm_${{ steps.scala.outputs.group1 }}_1.0

      - name: Remove Older Releases
        uses: smartsquaregmbh/delete-old-packages@v0.2.0
        with:
          keep: 2
          version-pattern: .*[^SNAPSHOT]$
          names: |
            com.harana.sbt.common_${{ steps.scala.outputs.group1 }}_1.0
            com.harana.sbt.js_${{ steps.scala.outputs.group1 }}_1.0
            com.harana.sbt.jvm_${{ steps.scala.outputs.group1 }}_1.0
            com.harana.sbt.js_jvm_${{ steps.scala.outputs.group1 }}_1.0

      - name: Notify Slack - Success
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_FOOTER: ""
          SLACK_MESSAGE: "✅  sbt-plugin  |  publish  |  ${{ steps.ref.outputs.replaced }}"
          SLACK_WEBHOOK: ${{ secrets.SLACK_BUILDS_WEBHOOK }}

      - name: Notify Slack - Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_FOOTER: ""
          SLACK_MESSAGE: "⛔️  sbt-plugin  |  publish  |  ${{ steps.ref.outputs.replaced }}"
          SLACK_WEBHOOK: ${{ secrets.SLACK_BUILDS_WEBHOOK }}